kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default # your namespace
  name: jenkins-access # Role name will be needed for binding to user
rules:
  - apiGroups: ["", "apps", "extensions"] 
    resources: ["pods", "services", "secrets", "deployments", "configmaps", "persistentvolumeclaims", "namespaces", "replicasets"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]

